export const throwError = () => {
  throw new Error("An error occurred while calling this function");
};
